logs_path: '/export/scratch1/home/aleksand/s2/PBT-NAS/logs'

out_name_template: "{dataset_name}_{algorithm}_pop{population_size}_Gan"

seed: 31173
seed_offset: 0
processes_per_gpu: 1
num_cpus: 2
n_seeds: 3

continue_auto: true

ssh_user: aleksand
ray_head_node: star03.scilens.private
if_shared_fs: false
final_upload_node: star04.scilens.private

cleanup_final: true

dataset_name: stl10advnas
dataset_parameters:
  dataset_path: '/export/scratch1/home/aleksand/s2/data/stl'
  train_batch_size: 128
  n_workers: 4

model_class: AdvNas
model_parameters:
  gf_dim: 270
  n_cells: 3
  n_cells_discr: 3
  bottom_width: 6
  latent_dim: 120
  g_activation: 'relu'
  df_dim: 128
  d_activation: 'relu'
  d_spectral_norm: true
  d_type: 'autogan'
  task: generation
  gan_target_res: 48
  if_search_projections: false
  generator_batch_size_multiplier: 2
  if_stl_projections: true

if_search_arch: true

optimizer_name: MyAdamW
lr: 0.0002
wd: 0.0
if_gen_avg: true

algorithm: RandomSearch
population_size: 24
max_epochs: 300
epochs_step: 10